 M .hermes_test.py
 M .hermes_test_result.txt
 M CLAUDE.md
 M README.md
 M SOUL.md
 M agent/__init__.py
 M agent/async_llm_client.py
 M agent/hermes.py
 M agent/llm_client.py
 M agent/tools/__init__.py
 M agent/tools/calc_tool.py
 M ai_agent_playground/agents/chat_agent.py
 M ai_agent_playground/base.py
 M ai_agent_playground/state_manager.py
 D check_env.py
 M memory/JOURNAL.jsonl
 M observability/tracer.py
 D requirements.txt
 M resume_matcher/data/liuzewen_resume.md
 D run_eval.py
 M run_stream_demo.py
 M scripts/e2e_test.py
 M scripts/stress_test.py
 D setup_eval.py.py
 M tests/conftest.py
 M tests/load_test.py
 M tests/test_async_core.py
 M tests/test_core_loop.py
 M uv.lock
?? _status.py
